### ISSUE TITLE
Complex "Bounty System"

### ISSUE THREAD

**Issue by MindsGaming** [Joystream/helpdesk#119]
Hello, I hope I am in the correct place. I have been exploring your video website [play.joysteam](https://play.joystream.org/) on the recommendation of a friend, and eventually looked into your project [main page](https://www.joystream.org/get-started); that lead me to your [test-net network portal](https://testnet.joystream.org/#) after clicking a bounty opportunity.  Once on that page I had to make a new account and add polkadot.js to my browser add-ons to continue.... Once this was done I could view the bounty only to go to the bottom of the five month old comments to see yet another membership I needed to interact with the bounty.
![ Joystream Network Portal-1](https://user-images.githubusercontent.com/19932832/155635382-4ebbe240-56ac-4f07-b92b-9e1e45094bb2.png)

After I click this I am taken to the membership page on the test-net where it tells me I need 100.00 Joy to become a member. So my question is pretty simple how does a new user complete a bounty if they have no test tokens to become a member and join these bounty, is there something I am missing here? 

After Thought
I also watched the last community call (9) about referrals and NFTs and glad you are coming out with some referral program for the video platform, is there already a referral link somewhere in my profile or is this a word of mouth thing, also what if a user doesn't have or want to join a discord,.. personally I don't have discord and don't like the closed nature of the code and not being able to know what they really do with data. Is there another way to get involved do you have a community chat on play?

**Comment by mochet** [comment]
Hi @MindsGaming !
Welcome! Thank you for posting, apologies for the difficulty in understanding the project and thanks for taking the time to put these questions together, I've tried to answer everything but if you have any more questions feel free to ask. The project is a bit complex, so my response is a little long, but I very much hope you join, there are some great opportunities available. I have also included some immediate things you can do for rewards (up to $55 or more, just for you! part of it just from joining our Telegram and the other part from answering questions at the bottom of this response)

There is a "giant upgrade" of the website and testnet which is coming out quite soon which will hopefully improve a lot of the problems you encountered, this is not only an improved website but includes huge upgrades to the project's blockchain. Please join our Telegram server (https://t.me/JoyStreamOfficial) and there are people there more than willing to help you with any questions you have.

1. If you join our Telegram please mention that you are @MindsGaming, share an address (you need to generate one either using the polkadot-js extension or the testnet website) and I'll send you some extra tokens ($15 worth) as a welcoming present (: I am `tomato` btw, so just ask for me!
2. I have also included a few questions at the end as an immediate way you can earn some extra tokens (an extra $20-$40 depending on the quality of answers--maybe even more if they're really great). All of these rewards will be paid in our testnet token (tJOY) which you can then exchange for Bitcoin Cash.

### Responses to your questions:
1. **Discord:** it is not a problem if you do not use Discord as we also have a Telegram server (https://t.me/JoyStreamOfficial)--there are users there who will be more than happy to help you. The Discord is where a large amount of activity happens but regardless of that, our project has many on-chain features (such as the forum) that allow it to function without relying on Discord or any platform like it--you can still fully participate without using Discord (it is more a tool of convenience, I am not the biggest fan of it myself)
2. **New users + tokens:** Anyone can join our Discord/Telegram at any time and ask for tokens and they will get them. The "giant upgrade" will include ways for users to get tokens or be invited (which gives tokens) through the testnet website. There is also a token faucet on Discord. (the "giant upgrade" will include a faucet within the testnet as well as an invitation system)
3. **The website:** is a little outdated which I apologize for--there is an entirely new system+website launching quite soon (maybe 1-2 weeks) and there will be a much more improved bounty system. In short we are going to transition to a new testnet which is the most significant advancement to the project so far, it not only includes a large amount of new features and improvements but also includes an entirely new UI for accessing the testnet/blockchain. It will also have a lot of new opportunities like far more bounties available!
4. **The forum thread you posted a screenshot of:** is actually for a weekly bounty, so that is an older thread. The most recent one is here: https://testnet.joystream.org/#/forum/threads/956
5. **Referral system:** Yes, there is a referral system however it has not fully launched yet. Once the "giant upgrade" I mentioned previously launches it will be possible to do so. There won't be referral links, however when a new user joins, they will be able to mention who has referred them. To maximize what you can earn from this, I would suggest waiting for the "giant upgrade", but participating from now and learning how to use the project's features will really help you for when the new system launches.

### Questions for you
Some questions for you (these are for the extra $20-$40 or more--if you give each answer a decent reply you will basically get the full amount!). You can just insert your answers after each question.

Please answer as you like, it is fine if you don't know answers or want to skip some. I don't need any private information.

If you don't want to write answers here, you can message me directly once you've joined our Telegram group and answer in a private chat with me, in which case the answers won't be shared publicly unless I ask you for permission first.

* General
	* How do you first get into crypto? Have you been participating for a long or short time?
* Communication / Chat
	* `Is there another way to get involved do you have a community chat on play?` - Can you tell me what `Play` is? I'm not familiar with it and its hard to Google it. We are currently looking at Discord alternatives and already have a Telegram as well as a Matrix server, so I would be very interested to know more about this.
	* Since you do not use Discord, what other chat programs do you use?
* Crypto questions
	* Communities (chat groups that discuss cryptocurrency projects)
		* You said a friend referred you to this project, were they a part of a crypto community?
			* Did they mention anything about this project in particular that attracted you to it?
		* Are there any communities you are a part of that talk about cryptocurrency projects? Are they public or private? If public could you share names?
		* Have you found projects recommended by any of these communities to be valuable?
		* What makes you trust these communities?
		* Are there some you do not trust? if so why do you not trust them? (you do not need to name specific communities, just general information) 
	* Crypto projects
		* Do you participate in projects that are mainly within Ethereum, Polkadot, Solana or others? If so, what's the reason for this?
		* If you participate in other projects, how long do you typically participate for? Do you participate in multiple projects?
	* News and information
		* Do you follow any particular people on Twitter, YouTube or other platforms that you find to be good for crypto information?
		* Do you read or follow any news websites that you find to be good for crypto information?
	* Ambassador programs
		* Have you participated in any ambassador programs or any sort of projects where you were given mainnet tokens? (without investing)
	* Bounty questions
		* Have you participated in bounties on other crypto projects?
		* What kind of work/bounties did you complete?
		* What amount of payment (roughly) did you receive?
		* Did your work require grading by someone? How long did it take?
		* How quickly did you receive rewards?
		* After completing bounties, did you find enough further bounties to do? Or was this limited?
		* Are there any particular type of bounties you are really interested in doing? Do you have any skills or interests you would like to explore?
* Joystream specific
	* Please don't Google or read the project's website for this section, if you aren't aware of something please say so as I'm asking these to understand the experience of a new user.
		* What aspects of this project make it interesting? Technology, money, NFTs, being a part of something that is big?
		* Are you aware our project is a DAO? Have you participated on other DAOs? Do you have any impressions about our project you would like to share?
		* For the bounty you posted (and all other bounties on our project) how do you think they are paid, as in how do you think the tokens are generated?
		* Were you aware that the forum post you shared is actually hosted on-chain? It isn't a normal forum, but is actually hosted by our blockchain (as seen here: https://telemetry.joystream.org/#map/Joystream)
		* Were you aware that on top of bounties our project actually has jobs available on-chain such as storage providers and content curators (and many others)?

**Comment by MindsGaming** [comment]
Hello and thanks for the amazing answers. I am very interested in finding a way to get involved and help, I will join your telegram soon I'm glad you have an open source alternative to discord for users. I can link telegram to my matrix sever so that will be nice.  I have also taken the time to answer the questions in your response email below. 

General
How do you first get into crypto? Have you been participating for a long or short time?

I got involved in cryptocurrency around 2015 playing games for Satoshi ( I say games really more like captchas).  I didnt really understand it back then or know what I was doing but foind it very interesting for some reason. I have kept tabs and followed its progress from then. I now even have my own ETH based token, and mostly use blockchains or cryptocurrency based websites.  My personal favorite is Minds.com (A crypto social media).


Communication / Chat
Is there another way to get involved do you have a community chat on play? - Can you tell me what Play is? I'm not familiar with it and its hard to Google it. We are currently looking at Discord alternatives and already have a Telegram as well as a Matrix server, so I would be very interested to know more about this.
Since you do not use Discord, what other chat programs do you use?

Sorry about that, "play" as in your subdomain play.joystream. I use the Maxtrix, an open sources decentralized chat sever you can own and mantain yourself.  
https://element.io/


Crypto questions
Communities (chat groups that discuss cryptocurrency projects)
You said a friend referred you to this project, were they a part of a crypto community?

Yes I am I am part of Minds.com and have a huge cryptocurrency based following 🥳

Did they mention anything about this project in particular that attracted you to it?

Yes, they liked the possibility of uplaoding music .mp3 to the blockchain they own (as a musician im gussing this is a good thing) they asked me to read your terms to make sure they would own thier music if they uploaded it to your sever.

Are there any communities you are a part of that talk about cryptocurrency projects? Are they public or private? If public could you share names?

My  cryptocurrency projects takes place in the Maxtrix (discord like chat server), Minds.com and my token trader Mintme.com all these places are public and accessable. 

Have you found projects recommended by any of these communities to be valuable?

We have been exploring cryptocurrency and blockchain projects together over the last year we haven't found much that really gives us all the tools we need, its a running joke on what new alpha product were trying this month 

What makes you trust these communities?
I built them overtime with hardwork and personal connection. #MindsGaming  

Are there some you do not trust? if so why do you not trust them? (you do not need to name specific communities, just general information).

I generally am very sceptical of all cryptocurrency projects, over my time ive seen many scams and rug pulls in the areana. Things to avoid are usually the same.

1.) Im not giving you anything 
No upfront cost or buying (you need tokens to do x) 
With all the available ways communities and projects can give rewards based off the blockchain im not interested if I have to buy something.

2.) Dont promise gains
 I quickly use interest (pun intended) if your project is vased of intrest of token value and not creating culture.

Crypto projects
Do you participate in projects that are mainly within Ethereum, Polkadot, Solana or others? If so, what's the reason for this?

I mostly participate in Ethereum as I have a token on the ethereum blockchain, however creator tokens and independent blockchains are going to be the next big thing. 
https://mintme.com/token/MTCG

If you participate in other projects, how long do you typically participate for? Do you participate in multiple projects?

I've partipated in Mind.com social from 2015 helping building and advancing the project from a points based system into a fully cryptocurrency token and rewards social media platform. 

I currently am not involved in any main projects as most of what can be accomplished fron a technical user based perspective is UI and features. 

News and information
Do you follow any particular people on Twitter, YouTube or other platforms that you find to be good for crypto information?
No they are pretty worthless 😂

Do you read or follow any news websites that you find to be good for crypto information?
Not that I can think of, most information is passed along person to person in our community.

Ambassador programs
Have you participated in any ambassador programs or any sort of projects where you were given mainnet tokens? (without investing).
Yes, Minds.com rewards users with Minds tokens for creating content on the platform. You can also create a token freely on Mintme.com and start traiding it for Mintme Coin that can be traded for ETH, BTH, USDC, BNB, and MTCG( lol MTCG is my token lol)

Bounty questions
Have you participated in bounties on other crypto projects?
Yes.
What kind of work/bounties did you complete?
- Blog Creation 
- Referral Links
- Uploaded Original Content
- Interaction With A Pro

What amount of payment (roughly) did you receive?
Did your work require grading by someone? How long did it take?
Usually payment of bountys is enough to stay involved freely in a project for contributing. In short its not enough to make money but enough to preform actions. I guess this answer maybe a little confusing but the best answer without a randomly generated number based on features.  

How quickly did you receive rewards?
I receive rewards daily (24 hours).

After completing bounties, did you find enough further bounties to do? Or was this limited?
Limited availably for bountys. However rewards are not limited and based off community flux.

Are there any particular type of bounties you are really interested in doing? Do you have any skills or interests you would like to explore?

I am a podcast/blogger that has my own cryptocurrency, community, groups, chat rooms and NFTs I could think of a million things that would interet me like streaming, creator tokens and more.

Joystream specific
Please don't Google or read the project's website for this section, if you aren't aware of something please say so as I'm asking these to understand the experience of a new user.

What aspects of this project make it interesting? Technology, money, NFTs, being a part of something that is big?
Non of the above, Im looking for a place to grow my community and skills on a product I can influence for a better cryptocurrency culture.

Are you aware our project is a DAO? Have you participated on other DAOs? Do you have any impressions about our project you would like to share?
No wasnt aware that it was a DAO or where I can stake a claim. My first impression is it looks interesting and a great idea but lacking (ALOT) in the UI.  I understand some onboarding updates are taking place but the current state of the site is complex and hard to understand even for a user who knows thier way around the blockchain.

For the bounty you posted (and all other bounties on our project) how do you think they are paid, as in how do you think the tokens are generated?
Im not sure how to answer this, all ethereum tokens are made the same way. You're on the testnet so they are not real tokens. 

Were you aware that the forum post you shared is actually hosted on-chain? It isn't a normal forum, but is actually hosted by our blockchain (as seen here: https://telemetry.joystream.org/#map/Joystream)
Were you aware that on top of bounties our project actually has jobs available on-chain such as storage providers and content curators (and many others)?

Yes I noted your forum was onchain when I had to install polkadot.js ; I am not aware you had jobs for content curators this is what I do, do you have a link?

**Comment by MindsGaming** [comment]
Also can you provide me with your Matrix room 😇

**Comment by mochet** [comment]
@MindsGaming thanks for the response! I'm going out for the evening, so I will respond to this tomorrow!

> Also can you provide me with your Matrix room 😇

https://matrix.to/#/#js-general:matrix.org - However there aren't many people constantly on it, so you may not find quick help there. If you want to chat we could do it tomorrow sometime?

**Comment by MindsGaming** [comment]
Thanks I have joined the Matrix room with some of my friends who want to come along on the adventure we would love to talk to you whenever you're around.

**Comment by mochet** [comment]
> Thanks I have joined the Matrix room with some of my friends who want to come along on the adventure we would love to talk to you whenever you're around.

Great! I let our community know there may be some people on the Matrix. I won't personally be there just yet, but hopefully tomorrow and almost anytime I'll be around to say hi!

**Comment by mochet** [comment]
Based upon this: https://github.com/Joystream/helpdesk/issues/119#issuecomment-1050787111
- I have elected to reward this user $70 USD (current exchange rate is $0.0000217--so 3,225,806 tJOY
- Transaction: https://pioneer.joystreamstats.live/#/explorer/query/0x54a969140334434e75a9d3cf387590472909c809b96058373313cca9bf075d46
- This reward comes from an account that has been funded by the council (https://pioneer.joystreamstats.live/#/proposals/1031) for the purpose of incentivizing new users and is managed by Tomato

**Comment by MindsGaming** [comment]
We are closing this issue as we now have access to matrix  and a participating founding member and have opened a user feature request idea:  https://github.com/Joystream/atlas/issues/2191
